In [6]:
import sys, os
sys.path.append('../')
import time
import numpy as np

from experiment.g_and_k import likelihood_MLMC, likelihood_MC, posterior_MLMC, posterior_MC

In [20]:
config_mlnle = {
    "task": "likelihood",
    "type": "mlmc",
    "epochs": 500,
    "n_list": [1000, 500],
    "m": 1,
}

config_nle = {""
    "task": "likelihood",
    "type": "mc",
    "epochs": 500,
    "n": 2000,
    "high": True,
    "m": 1
}

config_mlnpe = {
    "task": "posterior",
    "type": "mlmc",
    "epochs": 100,
    "n_list": [1000, 500],
    "m": 1000,
    "summary_dim": 4
}

config_npe = {
    "task": "posterior",
    "type": "mc",
    "epochs": 100,
    "n": 2000,
    "m": 1000,
    "summary_dim": 4,
    "high": True
}

In [9]:
time_mat = np.zeros((10, 4))

In [10]:
for i in range(10):
    start = time.time()
    likelihood_MLMC(config_mlnle)
    end = time.time()
    time_mat[i, 0] = end - start
    print("ML-NLE 1000 epochs time: ", end - start)

Device:  cpu


100%|██████████| 500/500 [00:01<00:00, 261.67it/s]


ML-NLE 1000 epochs time:  1.916830062866211
Device:  cpu


100%|██████████| 500/500 [00:01<00:00, 272.64it/s]


ML-NLE 1000 epochs time:  1.8360261917114258
Device:  cpu


100%|██████████| 500/500 [00:01<00:00, 274.91it/s]


ML-NLE 1000 epochs time:  1.8210442066192627
Device:  cpu


100%|██████████| 500/500 [00:01<00:00, 278.69it/s]


ML-NLE 1000 epochs time:  1.7962398529052734
Device:  cpu


100%|██████████| 500/500 [00:01<00:00, 271.99it/s]


ML-NLE 1000 epochs time:  1.8404381275177002
Device:  cpu


100%|██████████| 500/500 [00:01<00:00, 285.13it/s]


ML-NLE 1000 epochs time:  1.7557580471038818
Device:  cpu


100%|██████████| 500/500 [00:01<00:00, 265.10it/s]


ML-NLE 1000 epochs time:  1.8881678581237793
Device:  cpu


100%|██████████| 500/500 [00:01<00:00, 275.25it/s]


ML-NLE 1000 epochs time:  1.818701982498169
Device:  cpu


100%|██████████| 500/500 [00:01<00:00, 286.64it/s]


ML-NLE 1000 epochs time:  1.7464988231658936
Device:  cpu


100%|██████████| 500/500 [00:01<00:00, 281.91it/s]

ML-NLE 1000 epochs time:  1.7758331298828125


In [11]:
for i in range(10):
    start = time.time()
    likelihood_MC(config_nle)
    end = time.time()
    time_mat[i, 1] = end - start
    print("NLE 1000 epochs time: ", end - start)

Device:  cpu


Epoch: 499: 100%|██████████| 500/500 [00:01<00:00, 304.33it/s, loss=0.6388]


NLE 1000 epochs time:  1.647202968597412
Device:  cpu


Epoch: 499: 100%|██████████| 500/500 [00:01<00:00, 317.39it/s, loss=0.7239]


NLE 1000 epochs time:  1.577434778213501
Device:  cpu


Epoch: 499: 100%|██████████| 500/500 [00:01<00:00, 337.06it/s, loss=0.6817]


NLE 1000 epochs time:  1.4853010177612305
Device:  cpu


Epoch: 499: 100%|██████████| 500/500 [00:01<00:00, 313.84it/s, loss=0.6111]


NLE 1000 epochs time:  1.5957210063934326
Device:  cpu


Epoch: 499: 100%|██████████| 500/500 [00:01<00:00, 294.70it/s, loss=0.6313]


NLE 1000 epochs time:  1.699650764465332
Device:  cpu


Epoch: 499: 100%|██████████| 500/500 [00:01<00:00, 316.33it/s, loss=0.5118]


NLE 1000 epochs time:  1.5831389427185059
Device:  cpu


Epoch: 499: 100%|██████████| 500/500 [00:01<00:00, 329.38it/s, loss=0.5403]


NLE 1000 epochs time:  1.5201449394226074
Device:  cpu


Epoch: 499: 100%|██████████| 500/500 [00:01<00:00, 319.60it/s, loss=0.5952]


NLE 1000 epochs time:  1.5664126873016357
Device:  cpu


Epoch: 499: 100%|██████████| 500/500 [00:01<00:00, 315.96it/s, loss=0.6033]


NLE 1000 epochs time:  1.5849740505218506
Device:  cpu


Epoch: 499: 100%|██████████| 500/500 [00:01<00:00, 316.41it/s, loss=0.7471]

NLE 1000 epochs time:  1.5824592113494873


In [15]:
for i in range(10):
    start = time.time()
    posterior_MLMC(config_mlnpe)
    end = time.time()
    time_mat[i, 2] = end - start
    print("ML-NPE 500 epochs time: ", end - start)

100%|██████████| 100/100 [00:04<00:00, 24.88it/s]


ML-NPE 500 epochs time:  4.166680097579956


100%|██████████| 100/100 [00:03<00:00, 25.05it/s]


ML-NPE 500 epochs time:  4.102124929428101


100%|██████████| 100/100 [00:04<00:00, 24.83it/s]


ML-NPE 500 epochs time:  4.138895034790039


100%|██████████| 100/100 [00:03<00:00, 25.51it/s]


ML-NPE 500 epochs time:  4.023099184036255


100%|██████████| 100/100 [00:03<00:00, 26.01it/s]


ML-NPE 500 epochs time:  3.952531337738037


100%|██████████| 100/100 [00:03<00:00, 25.94it/s]


ML-NPE 500 epochs time:  3.958667039871216


100%|██████████| 100/100 [00:03<00:00, 25.97it/s]


ML-NPE 500 epochs time:  3.9568402767181396


100%|██████████| 100/100 [00:03<00:00, 25.28it/s]


ML-NPE 500 epochs time:  4.059952974319458


100%|██████████| 100/100 [00:03<00:00, 25.95it/s]


ML-NPE 500 epochs time:  3.95644211769104


100%|██████████| 100/100 [00:03<00:00, 26.32it/s]

ML-NPE 500 epochs time:  3.9030959606170654


In [21]:
for i in range(10):
    start = time.time()
    posterior_MC(config_npe)
    end = time.time()
    time_mat[i, 3] = end - start
    print("NPE 500 epochs time: ", end - start)

Epoch: 99: 100%|██████████| 100/100 [00:03<00:00, 31.32it/s, loss=5.6701]


NPE 500 epochs time:  3.335545063018799


Epoch: 99: 100%|██████████| 100/100 [00:03<00:00, 30.80it/s, loss=5.5976]


NPE 500 epochs time:  3.3606090545654297


Epoch: 99: 100%|██████████| 100/100 [00:03<00:00, 31.25it/s, loss=5.6538]


NPE 500 epochs time:  3.324937105178833


Epoch: 99: 100%|██████████| 100/100 [00:03<00:00, 32.51it/s, loss=5.6574]


NPE 500 epochs time:  3.1990089416503906


Epoch: 99: 100%|██████████| 100/100 [00:03<00:00, 30.87it/s, loss=5.6284]


NPE 500 epochs time:  3.3540329933166504


Epoch: 99: 100%|██████████| 100/100 [00:03<00:00, 31.17it/s, loss=5.6898]


NPE 500 epochs time:  3.323464870452881


Epoch: 99: 100%|██████████| 100/100 [00:03<00:00, 32.59it/s, loss=5.6318]


NPE 500 epochs time:  3.1932013034820557


Epoch: 99: 100%|██████████| 100/100 [00:03<00:00, 32.23it/s, loss=5.7789]


NPE 500 epochs time:  3.216646194458008


Epoch: 99: 100%|██████████| 100/100 [00:03<00:00, 32.56it/s, loss=5.6657]


NPE 500 epochs time:  3.186034917831421


Epoch: 99: 100%|██████████| 100/100 [00:03<00:00, 31.47it/s, loss=5.7078]

NPE 500 epochs time:  3.2908742427825928


In [35]:
time_mat.mean(axis=0)

array([1.81955383, 1.58424404, 4.0218329 , 3.27843547])

In [28]:
time_per_epoch = time_mat / np.array([1000, 1000, 500, 500])

In [31]:
time_per_epoch.shape

(10, 4)

In [32]:
time_per_epoch.mean(axis = 0)

array([0.00181955, 0.00158424, 0.00804367, 0.00655687])

In [34]:
time_per_epoch.std(axis = 0)

array([5.17136025e-05, 5.62867114e-05, 1.72019646e-04, 1.35650985e-04])